#!/usr/bin/env Rscript

library(knitr)

rmd = commandArgs(TRUE)
if (length(rmd) != 1L)
  stop("Exactly one file name must be provided")
if (!file.exists(rmd))
  stop("File not found")

render_jekyll()
opts_chunk$set(base_url = "/", fig.path = "_figures/", dev = "svg")
md = file.path("_posts", sub("\\.Rmd$", ".md", basename(rmd)))
knit(input = rmd, output = md)

# vim: ft=r
