#!/usr/bin/env Rscript

library(knitr)

rmd = commandArgs(TRUE)
if (length(rmd) != 1L)
  stop("Exactly one file name must be provided")
if (!file.exists(rmd))
  stop("File not found")

setwd(dirname(rmd))
rmd = basename(rmd)
render_jekyll()
opts_chunk$set(base.url = "/", dev = "svg", fig.path = file.path("..","figures",sub("\\.Rmd$", "/", rmd)), fig.width=7, fig.height=6)
md = file.path("..", "_posts", sub("\\.Rmd$", ".md", rmd))
knit(input = basename(rmd), output = md)

# vim: ft=r
