#!/usr/bin/env bash

# halt script on error
set -e

# check building the site
bundle exec jekyll build

# check html output (do not skip any testing)
bundle exec htmlproofer --http-status-ignore "0,999,429,403" ./_site
